name: BuildTestDeploy
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.runsettings'
      - 'LICENSE.txt'
      - 'README.md'

env:
  SOLUTION_FILE: Vectron.Extensions.Logging.TextBlock.sln
jobs:
  call-build-test:
    uses: Vectron/GithubWorkflows/tree/main/.github/workflows/BuildAndTest.yml@main
    with:
      os: windows-latest
      dotnet_version: 7.0.x
      solution_file: ${{ env.SOLUTION_FILE }}

  call-deploy:
    uses: Vectron/GithubWorkflows/tree/main/.github/workflows/DeployNugetGithub.yml@main
    with:
      os: windows-latest
      dotnet_version: 7.0.x
      solution_file: ${{ env.SOLUTION_FILE }}
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      

  call-release:
    uses: Vectron/GithubWorkflows/tree/main/.github/workflows/CreateRelease.yml@main
